### ISSUE TITLE
Options - Clicking on "Edit color" leads to nothing

### ISSUE THREAD

**Issue by abidrana7** [Gapminder/tools-page#101]
**CHARTS:** All Charts.
**ENV:** Live & Stage.

**STEPS TO REPRODUCE:**
1. Navigate to https://www.gapminder.org/tools
2. Click the “Options” from right lower side and than “color”.
3. Click the any regions from “world Region” i-e- The Americas.
4. Observe that three options appears while 3rd one “Edit color” is not clickable.

**ACTUAL RESULTS:**
Clicking on "Edit color" lead to happen nothing.

**EXPECTED RESULTS:** 
Although this is kept intentional BUT a tooltip should appear explaining why you can’t click it.

![Edit color is not clickable](https://user-images.githubusercontent.com/16793789/59127881-186c1100-8982-11e9-97b3-a08d9c64020c.png)

**Comment by angieskazka** [comment]
issue moved https://github.com/vizabi/vizabi-shared-components/issues/8
