### ISSUE TITLE
Can't build package

### ISSUE THREAD

**Issue by jane-taleika** [Gapminder/tools-page#108]
trying to build package, get error:

ERROR in   Error: internal/modules/cjs/loader.js:800
          throw err;
          ^
      Error: Cannot find module '!!../node_modules/lodash/lodash.js'
      Require stack:
      - D:\Personal\vizabi\tools-page-development\node_modules\html-webpack-plugin\index.js
      - D:\Personal\vizabi\tools-page-development\webpack.config.js
      - D:\Personal\vizabi\tools-page-development\node_modules\webpack-cli\bin\convert-argv.js
      - D:\Personal\vizabi\tools-page-development\node_modules\webpack-cli\bin\cli.js
      - D:\Personal\vizabi\tools-page-development\node_modules\webpack\bin\webpack.js
      
      - loader.js:797 Function.Module._resolveFilename
        internal/modules/cjs/loader.js:797:15
      
      - loader.js:690 Function.Module._load
        internal/modules/cjs/loader.js:690:27
      
      - loader.js:852 Module.require
        internal/modules/cjs/loader.js:852:19
      
      - v8-compile-cache.js:161 require
        [tools-page-development]/[v8-compile-cache]/v8-compile-cache.js:161:20
      
      - index.html:97 Object../node_modules/html-webpack-plugin/lib/loader.js!./src/index.html
        D:/Personal/vizabi/tools-page-development/src/index.html:97:9
      
      - index.html:21 __webpack_require__
        D:/Personal/vizabi/tools-page-development/src/index.html:21:30
      
      - index.html:85 
        D:/Personal/vizabi/tools-page-development/src/index.html:85:18
      
      - index.html:88 
        D:/Personal/vizabi/tools-page-development/src/index.html:88:10
      
      - index.js:247 HtmlWebpackPlugin.evaluateCompilationResult
        [tools-page-development]/[html-webpack-plugin]/index.js:247:28
      
      - index.js:161 
        [tools-page-development]/[html-webpack-plugin]/index.js:161:23
      
    Can you please provide your package-lock to check versions

**Comment by angieskazka** [comment]
@jane-taleika it's been a while here. are you still interested to build it?

**Comment by angieskazka** [comment]
updated readme for the building process
https://github.com/Gapminder/tools-page/blob/development/README.md

let me know if any questions arise

**Comment by jane-taleika** [comment]
Do you cover everything to prepare to start project in readme? Because I
have problems even with installing project (with protractor, I'll attach
log).
But even after removing postinstall script I have trouble with running app.
Both logs are attached.
My earlier problem was with installing due to protractor too, and I had
troubles with packages versions. Why do you not commit changes to
package-lock file?




ср, 19 авг. 2020 г., 15:42 Angie the Fairytale <notifications@github.com>:
