### ISSUE TITLE
investigate an URLON confusion

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#113]
`https://www.gapminder.org/tools/#$state$time$value=1947;;&ui$presentation:true;&chart-type=bubbles`

why is there `value=1947` in one situation and `presentation:true` in another?

sometimes both work, such as

`http://localhost:10001/tools/#$state$time$value=2017;;&ui$chart$maxRadiusEm=0.12;&chart-type=bubbles;&chart-type=bubbles`

and

`http://localhost:10001/tools/#$state$time$value=2017;;&ui$chart$maxRadiusEm:0.12;&chart-type=bubbles;&chart-type=bubbles`

note that `:0.12` doesn't get converted to `=0.12` in the URL as page loads

or

`https://www.gapminder.org/tools/#$state$time$value=1947;;&ui$presentation:true;&chart-type=bubbles`

and

`https://www.gapminder.org/tools/#$state$time$value:1947;;&ui$presentation:true;&chart-type=bubbles`

note that `:1947` does get converted to `=1947`

sometimes page errors when : or = is given but something else was expected (can't reproduce now)

anyway would be good to understand what's going on here

**Comment by jheeffer** [comment]
`:` signifies a non-string value
`=` signifies a string value

needed for unambiguous parsing in [urlon](https://github.com/cerebral/urlon)
