### ISSUE TITLE
Repeater component reads encodings outside of reactive context

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#143]
Repeater component is not run in an autorun()
Repeater component reads marker properties such as encodings outside of autorun
Any model of vizabi reactive should be accessed inside an autorun otherwise computed will not be cached / memoised

**Comment by jheeffer** [comment]
I hard coded repeater config temporarily

https://github.com/vizabi/vizabi-shared-components/commit/45d3c5ce942c95440403f9996888c7e2a7287e2e

**Comment by angieskazka** [comment]
fixed when refactoring repeater a while ago
