### ISSUE TITLE
BC: Trail error when bubble has completely no data

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#195]
Very similar to #190, but different steps to test here

Select Afghanistan
Make a trail
Set X to Electricity use / person

`TypeError: Cannot read property 'getByObjOrStr' of undefined at trail.js:82`

this again is the same place where i put protection against min max limits being undefined but then i removed it

**Comment by jheeffer** [comment]
@angieskazka What is expected behaviour?

Afghanistan being deselected & trailstart removed? Trails being turned off?

**Comment by jheeffer** [comment]
Fixed in https://github.com/vizabi/vizabi-reactive/commit/d9bba18df30b61430cdad1c3d87a97c566e09240

**Comment by jheeffer** [comment]
Actually I'll leave it to you to check if it's fixed & close it, Angie.

**Comment by angieskazka** [comment]
fixed in vizabi-reactive v1.5.0
