### ISSUE TITLE
Refreshing with constant/indicator color sends out invalid query

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/tools-page#200]
When color is set to constant or an indicator, color legend marker should not be accessed. Its config will be invalid (space set to empty or an indicator).

This is done well most of the time, except on initial load. E.g. click here

http://localhost:4200/tools/#$model$markers$bubble$encoding$color$data$space@=country&=time;&constant=_default;&scale$type:null;;;;;;&chart-type=bubbles&url=v1

or here

http://localhost:4200/tools/#$model$markers$bubble$encoding$color$data$space@=country&=time;&concept=child_mortality_0_5_year_olds_dying_per_1000_born;&scale$type:null;;;;;;&chart-type=bubbles&url=v1

[A one-off function deducing vizabi's default model](https://github.com/Gapminder/tools-page/blob/vizabi-reactive/src/app/core/tool.js#L183-L189) tries to read the legend marker when color is not set to an entity property, leading to invalid queries being sent.

**Comment by angieskazka** [comment]
Could be fixed in the above mentioned commit

**Comment by jheeffer** [comment]
Might not work with autoconfig since that needs at least availability & concepts to be loaded.
