### ISSUE TITLE
Flexible (fuzzy?) time feature

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#207]
I’d like the ”flexible time” feature. When last available year is different for different countries , we should have a slider under :gear:: where user can set an allowed range, between 0-20 e.g.  ”use data from nearby years: within 7 years”

**Comment by jheeffer** [comment]
I.e. extrapolation by copying, limited to latest year other markers are available or a maximum amount of steps.

**Comment by jheeffer** [comment]
"and preferably, the [extrapolated] marker should visually look different, to show it ws a different year."
