### ISSUE TITLE
BC: Transitions in and out of existence are confusing

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#219]
When playing over time, here, bubbles pop up ahead of time, when they start having available data, and after 2018 it suddenly uses quicker play speed than previous play: 

![image](https://user-images.githubusercontent.com/3648190/116139076-ea0e9080-a6d5-11eb-918d-6bb7f30ce531.png)

http://localhost:4200/tools/#$model$markers$bubble$encoding$y$data$concept=is_shp_good_tu&space@=country&=time;&source=wdi;&scale$domain:null&zoomed:null;;&x$data$concept=time&space@=time;;&scale$domain:null&zoomed:null&type:null;;;;;;&chart-type=bubbles&url=v1

**Comment by jheeffer** [comment]
What is expected behaviour for bubbles appearing/disappearing? Should they not fade in/out in place?

**Comment by jheeffer** [comment]
Ola: lets keep it the way it is.
