### ISSUE TITLE
"undefined" in URL when selecting anything

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/tools-page#228]
http://localhost:4200/tools/#$model$markers$bubble$encoding$selected$data$filter$markers$country-ind=undefined;;;;;;;;&chart-type=map&url=v1

**Comment by jheeffer** [comment]
Fixed by https://github.com/vizabi/vizabi-reactive/commit/7ec812e3d1498808eb19a96da4411338c4bbd82e
