### ISSUE TITLE
Income mountain

### ISSUE THREAD

**Issue by Falnesio** [Gapminder/tools-page#40]
Hello, thank you all for these wonderful tools.

Is there a way to stack the countries based on the mean income?
https://www.gapminder.org/tools/#$chart-type=mountain

**Comment by angieskazka** [comment]
thanks for the kind words, @Falnesio!

the countries are stacked in a 2-level method: first they are grouped by a certain classification, which matches with color. so when you for example select color --> categories --> 6 world region, you will get them re-grouped

within each group the slices are sorted by their size (confusingly called axis_y [here](https://github.com/vizabi/vizabi-mountainchart/blob/develop/src/component.js#L599)), which maps to population

by changing axis_y to axis_x you should get sorting by mean income

if you have skills in code you can do it yourself and use the modified tool for free, non-commercially and commercially according to the license.

however we aren't planning to add this as a feature in any of our live products
hope this helps

❤️
