### ISSUE TITLE
Popbyage - No usage of country's search.

### ISSUE THREAD

**Issue by abid71** [Gapminder/tools-page#79]
**AUT:** tools-pages.
**CHARTS:** Popbyage Chart.
**ENV:** Live & Dev.

**STEPS TO REPRODUCE:**
Navigate to URL: https://www.gapminder.org/tools/#$chart-type=popbyage
1) Search any country name in search box.
2) Note that nothing would happen at all.

**ACTUAL RESULTS:** on searching any country, no search hit appear, apply button would remain disable.
**EXPECTED RESULTS:** If search is nothing to do at popbyage - home page, it should not be visible there!

![no usage of countries s search in popbyage chart](https://user-images.githubusercontent.com/16793789/50378930-9fd8f880-065e-11e9-98c8-33c8a2fb79cf.png)

**Comment by abidrana7** [comment]
Actually, this bug is more related to responsive issue. Please see below screenshot. 

*RES:* 1366 x 768

![3](https://user-images.githubusercontent.com/16793789/57033435-592b8880-6c66-11e9-96b1-794ec99df26a.png)
