### ISSUE TITLE
Poverty line's value hide behind the `collapse-sidebar`

### ISSUE THREAD

**Issue by abid71** [Gapminder/tools-page#86]
**CHARTS:** Mountain Chart Only.
**ENV:** Live, Stage & Dev.

**STEPS TO REPRODUCE:**
 
1) Navigate to URL: https://www.gapminder.org/tools/#$chart-type=mountain
2) Hover the `poverty line` to extreme end of x-axis's value.
3) Observe that poverty line's value hide behind the `collapse-sidebar`

**ACTUAL RESULTS:** Poverty line's value hide behind the `collapse-sidebar`
**EXPECTED RESULTS:** Poverty line's value should not be hide when it come closer to 'collapse-sidebar'

![poverty line hide behind the sidebar collapse](https://user-images.githubusercontent.com/16793789/51206073-177e0880-1929-11e9-810b-3f57a7fa36a2.png)

**Comment by angieskazka** [comment]
it's ok @abid71, not worth fixing, because there is rarely anything happening on the edges of the chart
